import torch
import os # for deleting excess files generated by triton
from math import log2

import triton
import triton.language as tl
from triton.runtime import driver
import numpy as np

from utils import GenerateLinkedList

DEVICE = torch.device(f"cuda:{torch.cuda.current_device()}")
print("Using device:", DEVICE)

properties = driver.active.utils.get_device_properties(DEVICE.index)

print(f"properties:\n{properties}")